version: '3'

services:
  db:
    image: postgres:14.3
    container_name: teslo-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    # NOTA: comentar o eliminar el volumen para empezar siempre fresh
    volumes:
      - ./postgres:/var/lib/postgresql/data
